[project]
name = "cognitive-chat-control-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.12.0",
    "black>=26.1.0",
    "huggingface-hub>=1.5.0",
    "librosa>=0.10.0",
    "neo4j>=6.1.0",
    "openai>=2.33.0",
    "pillow>=10.0.0",
    "pydantic>=2.13.3",
    "python-dotenv>=1.0.0",
    "ruff>=0.14.14",
    "safetensors>=0.7.0",
    "soundfile>=0.13.0",
    "tiktoken>=0.12.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "transformers @ git+https://github.com/huggingface/transformers.git",
]
